version: '3'
services:
  # 基础环境
  nginx:
    container_name: mymall-nginx
    image: jahentao/mymall-nginx:1
    ports:
      - "80:80"
    extra_hosts:
      - "MYHOST:${MYHOST}"
      - "dubbo-admin.mymall.com:${MYHOST}"
      - "manage.mymall.com:${MYHOST}"
      - "item.mymall.com:${MYHOST}"
      - "mymall.com:${MYHOST}"
      - "www.mymall.com:${MYHOST}"
      - "image.mymall.com:${MYHOST}"
      - "static.mymall.com:${MYHOST}"
      - "sso.mymall.com:${MYHOST}"
      - "order.mymall.com:${MYHOST}"
      - "solr.mymall.com:${MYHOST}"
      - "search.mymall.com:${MYHOST}"
      - "cart.mymall.com:${MYHOST}"
  # 3个zookeeper构成的集群
  zookeeper:
    image: zookeeper
    restart: always
    hostname: zookeeper
    ports:
      - 2181:2181
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888 server.2=zookeeper2:2888:3888 server.3=zookeeper3:2888:3888
  zookeeper2:
    image: zookeeper
    restart: always
    hostname: zookeeper2
    ports:
      - 2182:2181
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zookeeper:2888:3888 server.2=0.0.0.0:2888:3888 server.3=zookeeper3:2888:3888
  zookeeper3:
    image: zookeeper
    restart: always
    hostname: zookeeper3
    ports:
      - 2183:2181
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zookeeper:2888:3888 server.2=zookeeper2:2888:3888 server.3=0.0.0.0:2888:3888
  
  
  redis:
    container_name: mymall-redis
    image: redis:3.2
    ports:
      - "6379:6379"
  db:
    container_name: mymall-mysql
    image: jahentao/mymall-mysql:1
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: mymall
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_ROOT_HOST: '%'
      TZ: Asia/Shanghai
  solr:
    container_name: mymall-solr
    image: jahentao/mymall-solr:1
    ports:
      - "8983:8983"
  activemq:
    container_name: mymall-activemq
    image: webcenter/activemq:5.14.3
    ports:
      - "61616:61616"
      - "8161:8161"
#   搞不定，fastdfs以docker-compose启动，配置哪里不对，上传文件用不了
#  fastdfs-tracker:
#    container_name: mymall-fastdfs-tracker
#    image: morunchang/fastdfs
#    command: sh tracker.sh
#    ports:
#      - "22122:22122"
#      - "8080:8080"
#  fastdfs-storage:
#    container_name: mymall-fastdfs-storage
#    build:
#      context: ./mymall-fastdfs-storage
#    image: mymall-fastdfs-storage:1
#    environment:
#      # IP 需要修改
#      TRACKER_IP: fastdfs-tracker:22122
#      GROUP_NAME: group1
#    command: sh storage.sh
#    ports:
#      - "23000:23000"
#      这个端口要修改，暂时不要用文件下载
#      - "80:80"


  # 应用服务，依赖基础环境
  #  docker-compose stop manager-service content-service search-service sso-service cart-service order-service
  #  docker-compose start manager-service content-service search-service sso-service cart-service order-service
  manager-service:
    container_name: mymall-manager-service
    image: jahentao/mymall-manager-service:1
    ports:
      - "20880:20880"
    depends_on:
      - db
      - redis
      - activemq
      - zookeeper
    links:
      - zookeeper
      - activemq
      - redis
      - db:mysql
  content-service:
    container_name: mymall-content-service
    image: jahentao/mymall-content-service:1
    ports:
      - "20881:20881"
    depends_on:
      - db
      - redis
      - zookeeper
    links:
      - db:mysql
      - redis
      - zookeeper
  search-service:
    container_name: mymall-search-service
    image: jahentao/mymall-search-service:1
    ports:
      - "20882:20882"
    depends_on:
      - db
      - solr
      - activemq
      - zookeeper
    links:
      - db:mysql
      - activemq
      - zookeeper
      - solr
  sso-service:
    container_name: mymall-sso-service
    image: jahentao/mymall-sso-service:1
    ports:
      - "20883:20883"
    depends_on:
      - db
      - redis
      - zookeeper
    links:
      - db:mysql
      - redis
      - zookeeper
  cart-service:
    container_name: mymall-cart-service
    image: jahentao/mymall-cart-service:1
    ports:
      - "20884:20884"
    depends_on:
      - db
      - redis
      - zookeeper
    links:
      - db:mysql
      - redis
      - zookeeper
  order-service:
    container_name: mymall-order-service
    image: jahentao/mymall-order-service:1
    ports:
      - "20885:20885"
    depends_on:
      - db
      - redis
      - zookeeper
    links:
      - db:mysql
      - redis
      - zookeeper

  # Dubbo监控
  dubbo-admin:
    container_name: mymall-app-dubbo-admin
    image: jahentao/mymall-dubbo-admin:1
    ports:
      - "7001:7001"
    depends_on:
      - zookeeper
    links:
      - zookeeper

  # Web应用
  #  docker-compose stop manager-web portal-web search-web item-web sso-web cart-web order-web
  #  docker-compose start manager-web portal-web search-web item-web sso-web cart-web order-web
  manager-web:
    container_name: mymall-app-manager-web
    image: jahentao/mymall-manager-web:1
    ports:
      - "8081:8081"
    depends_on:
      - zookeeper
      - content-service
      - manager-service
      - search-service
    links:
      - zookeeper
  portal-web:
    container_name: mymall-app-portal-web
    image: jahentao/mymall-portal-web:1
    ports:
      - "8082:8082"
    depends_on:
      - zookeeper
      - content-service
    links:
      - zookeeper
  search-web:
    container_name: mymall-app-search-web
    image: jahentao/mymall-search-web:1
    ports:
      - "8083:8083"
    depends_on:
      - zookeeper
      - redis
      - search-service
    links:
      - zookeeper
  item-web:
    container_name: mymall-app-item-web
    image: jahentao/mymall-item-web:1
    ports:
      - "8084:8084"
    depends_on:
      - zookeeper
      - activemq
      - manager-service
    links:
      - activemq
      - zookeeper
  sso-web:
    container_name: mymall-app-sso-web
    image: jahentao/mymall-sso-web:1
    ports:
      - "8085:8085"
    depends_on:
      - zookeeper
      - sso-service
    links:
      - zookeeper
  cart-web:
    container_name: mymall-app-cart-web
    image: jahentao/mymall-cart-web:1
    ports:
      - "8086:8086"
    depends_on:
      - zookeeper
      - cart-service
      - manager-service
      - sso-service
    links:
      - zookeeper
  order-web:
    container_name: mymall-app-order-web
    image: jahentao/mymall-order-web:1
    ports:
      - "8087:8087"
    depends_on:
      - zookeeper
      - cart-service
      - order-service
      - sso-service
    links:
      - zookeeper

#networks:
#  frontend:
#  backend:
#
#volumes:
#  db-data:s