#tomcat conf
server:
  port: 8083
#dubbo conf
spring:
  redis:
      timeout: 5000
  # redis-single
      host: 127.0.0.1
      port: 6379
dubbo:
  application:
    name: mymall-search-web
  registry:
      address: zookeeper://aliservice.maoyiwei.top:2181