mybatis:
  config-location: classpath:mybatis/SqlMapConfig.xml
  mapper-locations: classpath:mybatis/mapper/*.xml

spring:
  datasource:
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:123456}
    url: jdbc:mysql://${MYSQL_HOST:192.168.237.100}:${MYSQL_PORT:3307}/${MYSQL_DATABASE:mymall}
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    timeout: 5000
# redis-single
    host: ${REDIS_HOST:192.168.237.100}
    port: ${REDIS_PORT:6379}

dubbo:
  application:
    name: mymall-sso
  registry:
    address: zookeeper://${ZOOKEEPER_HOST:192.168.237.100}:${ZOOKEEPER_PORT:2181}
  scan:
    basePackages: cn.edu.zju.cst.sagroup.sso.service
  protocol:
    port: ${MYMALL_SSO_SERVICE_PORT:20883}