#dubbo conf
dubbo:
  application:
    name: mymall-manager-web
  registry:
      address: zookeeper://${ZOOKEEPER_HOST:192.168.237.100}:${ZOOKEEPER_PORT:2181}
#picture upload conf
spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 1MB
      max-request-size: 10MB
#tomcat conf
server:
  port: ${SERVER_PORT:8081}
