#tomcat conf
server:
  port: ${SERVER_PORT:8086}
#dubbo conf
dubbo:
  application:
    name: mymall-cart-web
  registry:
      address: zookeeper://${ZOOKEEPER_HOST:192.168.237.100}:${ZOOKEEPER_PORT:2181}