#tomcat conf
server:
  port: 8083
spring:
  redis:
    timeout: 5000
    # redis-single
    host: redis
    port: 6379
#dubbo conf
dubbo:
  application:
    name: mymall-search-web
  registry:
      address: zookeeper://zookeeper:2181