mybatis:
  config-location: classpath:mybatis/SqlMapConfig.xml
  mapper-locations: classpath:mybatis/mapper/*.xml

spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://192.168.237.100:3307/mymall
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    timeout: 5000
# redis-single
    host: 192.168.237.100
    port: 6379

dubbo:
  application:
    name: mymall-order
  registry:
    address: zookeeper://192.168.237.100:2181
  scan:
    basePackages: cn.edu.zju.cst.sagroup.order.service
  protocol:
    port: 20885